apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
      - name: devsecops-demo
        image: vishnupriyaaa/devsecops-demo:latest

        ports:
        - containerPort: 80
