name: Python Code Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest  # ✅ safest option; don’t specify a version like ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # ✅ this is how you tell it to use Python 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 .
